### PR TITLE
Correct the wrong shortcut

### PR DESCRIPTION
**Pull request by luspa**

### CODE REVIEW

**Comment by jaipandya** [comment]
Hey @luspa

<kbd>Ctrl</kbd> + <kbd>K</kbd> works well for deleting till the end of the line. Why do you want to change it?

**Comment by luspa** [comment]
Hi @jaipandya 

<kbd>Ctrl</kbd> + <kbd>K</kbd> does not work on my MacBook Air + Sublime 3, but <kbd>Ctrl</kbd> + <kbd>K</kbd> + <kbd>K</kbd> works.

**Comment by luspa** [comment]
Hi @jaipandya 

After some investigating, I found that <kbd>Ctrl</kbd> + <kbd>K</kbd> is being used by one of my packages.

It is my fault, just ignore this pull request, sorry.

**Comment by jaipandya** [comment]
Sure, no problems. Thanks for making this effort.

**Pull request closed without merging**
